### ISSUE TITLE
Ender 3 S1 version is feasible?

### ISSUE THREAD

**Issue by sdbruder** [synman/Ender-3-S1-Pro-Firmware#1]
If yes, there is an ETA? what is the effort to do that? How can I help?

**Comment by synman** [comment]
https://github.com/synman/Ender-3S1/tree/firmware_troubleshooting is my source branch.   If it were me, I'd be running the "Pro" firmware if I had any other the other S1s FWIW.

**Comment by synman** [comment]
Will look into adding the S1 Plus to the build list as it is locked out like the Pro.

**Comment by synman** [comment]
S1 Plus builds are now available
