### ISSUE TITLE
compile warning M300.cpp

### ISSUE THREAD

**Issue by ThomasToka** [synman/Ender-3-S1-Pro-Firmware#12]
Hi,
could you have a look at this warning:

`Compiling .pio\build\STM32F401RC_creality\src\src\gcode\parser.cpp.o
Marlin\src\gcode\lcd\M300.cpp: In static member function 'static void GcodeSuite::M300()':
Marlin\src\gcode\lcd\M300.cpp:40:18: warning: unused variable 'frequency' [-Wunused-variable]
   40 |   uint16_t const frequency = parser.ushortval('S', 260);
      |                  ^~~~~~~~~
Compiling .pio\build\STM32F401RC_creality\src\src\gcode\probe\G30.cpp.o`

**Comment by synman** [comment]
Yup... This is NBD

**Comment by synman** [comment]
A result of enabling speaker control (still a work in progress)
