### ISSUE TITLE
Increase max bed temp via LCD

### ISSUE THREAD

**Issue by synman** [synman/Ender-3-S1-Pro-Firmware#15]
Should at least be able to see 120C.  Best case is to use max bed temp via cfg.

**Comment by synman** [comment]
Really annoying.  This appears the one function where a max value is hardcoded within the actual LCD firmware.  The handler in lcd_rts is never called when the LCD receives a bed temperature > 110C

**Comment by IAGITH** [comment]
well.. the bed isnt rated for any more than 110... so i think that could be a fire hazard?? idk

**Comment by synman** [comment]
Via firmware the max is 120.  You can take it there today via an external sender.  It's merely the touchscreen is hardcoded for 110.
