### ISSUE TITLE
UBL 100 Fails at point 28 - F4-s1pro - Octoprint

### ISSUE THREAD

**Issue by MrDB42** [synman/Ender-3-S1-Pro-Firmware#32]
When running bed leveling, the probe retracts at "Probing mesh point 28/100" and an error is thrown when connected via Octoprint.

Recv: //action:notification Probing Failed
Recv: Error:Probing Failed
Changing monitoring state from "Operational" to "Error"

When Octoprint receives the error it halts the system.

Happens with either the "bugfix-2.1.x-F4-s1pro_ubl100" or "2.1.2-ender-3-s1-F4-s1pro_ubl100" versions.

**Comment by MrDB42** [comment]
Oh, just figured out that it's only when connected via Octoprint. Octoprint will halt the system.

**Comment by synman** [comment]
Tweak Octoprint to not fail / halt on all errors.

**Comment by MrDB42** [comment]
Oh... That's _cheating_! ;)

I was starting to wonder if my probe was the issue. But if you're running into the same problem, I wonder what the root cause of the errors are?

**Comment by MrDB42** [comment]
And... even if I disconnect via Octoprint, running the bed level from the LCD screen, it will eventually lock up completely.

It gets to 100%, then it starts over and hangs at 3%. Weird.

The UBL25 works just fine, BTW.

**Comment by synman** [comment]
Have you read the UBL discussion?  Check it out if not as it gives a ton of pointers.

My guess is it's the CR touch flaking out and / or an upstream bug in Marlin.

You're going to find a couple scenarios where Marlin will issue an error where you don't want Octoprint to disconnect.  There are a couple options there you'll want to look at.

**Comment by synman** [comment]
Let's move this to the UBL discussion thread

**Comment by synman** [comment]
Let's move this to the UBL discussion thread
