### ISSUE TITLE
Make firmwares open source

### ISSUE THREAD

**Issue by wirelessnet2** [synman/Ender-3-S1-Pro-Firmware#59]
Could you please make the source code for 2.0.8, 2.1.2, and bugfix 2.1.2 publicly available on github alongside the precompiled binaries? This would make it much easier to make changes.

For example, I'd like to enable the M575 Baud Rate command. Thanks!

**Comment by DaveLinger** [comment]
I would also like this, because I like the Professional firmware the way it is EXCEPT I'd like to increase the probing margin, which I guess has to be changed in configuration.h, then recompiled. I don't want to lose all of this firmware's perks just to adjust the probing margin.

**Comment by wcole3** [comment]
Are you asking for something other than the forks linked at the end of the readme?
