### ISSUE TITLE
Enable SOUND

### ISSUE THREAD

**Issue by synman** [synman/Ender-3-S1-Pro-Firmware#9]
M300 and any built in "beep" type events should use the S1's buzzer.

**Comment by synman** [comment]
not as simple as adding speaker and using the rts_ui `rtscheck.RTS_SndData(StartSoundSet, SoundAddr)` method to M300

**Comment by synman** [comment]
Has anyone ever heard their LCD beep for anything other than a touch event on the screen?

There is code inside of rts_ui for triggering a beep.  It is used in multiple places (mainly around power recovery / sd printing).  However, addressing that address while talking to the LCD does nothing.

**Comment by MrDB42** [comment]
I've NEVER gotten a beep out of my LCD screen, except for touch events.
